# Generated by Django 3.2.4 on 2021-06-12 15:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 12, 15, 4, 24, 165086, tzinfo=utc)),
        ),
    ]
