# Generated by Django 3.2.4 on 2021-06-13 15:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_auto_20210613_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='filename',
        ),
        migrations.AddField(
            model_name='items',
            name='bought',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='items',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 13, 15, 46, 18, 202383, tzinfo=utc)),
        ),
    ]
